# Transformada de fourier

In [23]:
import cv2
import numpy as np
from scipy import ndimage

In [24]:
kernel_3x3 = np.array([[-1, -1, -1],
                       [-1, 8, -1],
                       [-1, -1, -1]])

kernel_5x5 = np.array([[-1, -1, -1, -1, -1],
                       [-1, 1, 2, 1, -1],
                       [-1, 2, 4, 2, -1],
                       [-1, 1, 2, 1, -1],
                       [-1, -1, -1, -1, -1]])

img = cv2.imread("sources/estatua.jpg", cv2.IMREAD_GRAYSCALE)

k3 = ndimage.convolve(img, kernel_3x3) 
k5 = ndimage.convolve(img, kernel_5x5)

blurred = cv2.GaussianBlur(img, (17,17), 0)

g_hpf = img - blurred

print(img)
print(blurred)




cv2.imshow("original", img)
cv2.imshow("k3", k3)
cv2.imshow("k5", k5)
cv2.imshow("blurred", blurred)
cv2.imshow("filtro", g_hpf)

cv2.waitKey()
cv2.destroyAllWindows()

#cv2.waitKey()
#cv2.destroyAllWindows()




#k3 = ndimage.convolve(img, kernel_3x3) 
                 
#k5 = ndimage.convolve(img, kernel_5x5)

#blurred = cv2.GaussianBlur(img, (17,17), 0)
#g_hpf = img - blurred

#cv2.imshow("3x3", k3)
#cv2.imshow("5x5", k5)
#cv2.imshow("blurred", blurred)
#cv2.imshow("g_hpf", g_hpf)
#cv2.waitKey()
#cv2.destroyAllWindows()



[[148 148 148 ...  84  72  97]
 [148 149 149 ...  99  98  82]
 [149 149 149 ...  97  84  31]
 ...
 [184 183 183 ... 179 191 200]
 [184 185 183 ... 192 187 190]
 [184 185 183 ... 198 191 191]]
[[149 149 149 ...  77  76  76]
 [149 149 149 ...  76  75  75]
 [149 149 149 ...  73  73  72]
 ...
 [181 181 181 ... 186 193 196]
 [182 181 181 ... 183 191 193]
 [182 182 181 ... 182 190 192]]


# Creating modules

In [22]:
class saludar(object):
    def __init__(self, nombreMundo):
        self._nombreMundo = nombreMundo
    
    def __str__(self):
        return f"Joder {self._nombreMundo}"
        
    def imprimir(self):
        print("Hola mundo " + self._nombreMundo)
        

x = saludar("Terricola")
y = saludar("Avicola")

x.imprimir()      
y.imprimir()      

print(y)
print(x)
    

Hola mundo Terricola
Hola mundo Avicola
Joder Avicola
Joder Terricola
