# Transformada de fourier

In [23]:
import cv2
import numpy as np
from scipy import ndimage

In [24]:
kernel_3x3 = np.array([[-1, -1, -1],
                       [-1, 8, -1],
                       [-1, -1, -1]])

kernel_5x5 = np.array([[-1, -1, -1, -1, -1],
                       [-1, 1, 2, 1, -1],
                       [-1, 2, 4, 2, -1],
                       [-1, 1, 2, 1, -1],
                       [-1, -1, -1, -1, -1]])

img = cv2.imread("sources/estatua.jpg", cv2.IMREAD_GRAYSCALE)

k3 = ndimage.convolve(img, kernel_3x3) 
k5 = ndimage.convolve(img, kernel_5x5)

blurred = cv2.GaussianBlur(img, (17,17), 0)

g_hpf = img - blurred

print(img)
print(blurred)




cv2.imshow("original", img)
cv2.imshow("k3", k3)
cv2.imshow("k5", k5)
cv2.imshow("blurred", blurred)
cv2.imshow("filtro", g_hpf)

cv2.waitKey()
cv2.destroyAllWindows()

#cv2.waitKey()
#cv2.destroyAllWindows()




#k3 = ndimage.convolve(img, kernel_3x3) 
                 
#k5 = ndimage.convolve(img, kernel_5x5)

#blurred = cv2.GaussianBlur(img, (17,17), 0)
#g_hpf = img - blurred

#cv2.imshow("3x3", k3)
#cv2.imshow("5x5", k5)
#cv2.imshow("blurred", blurred)
#cv2.imshow("g_hpf", g_hpf)
#cv2.waitKey()
#cv2.destroyAllWindows()



[[148 148 148 ...  84  72  97]
 [148 149 149 ...  99  98  82]
 [149 149 149 ...  97  84  31]
 ...
 [184 183 183 ... 179 191 200]
 [184 185 183 ... 192 187 190]
 [184 185 183 ... 198 191 191]]
[[149 149 149 ...  77  76  76]
 [149 149 149 ...  76  75  75]
 [149 149 149 ...  73  73  72]
 ...
 [181 181 181 ... 186 193 196]
 [182 181 181 ... 183 191 193]
 [182 182 181 ... 182 190 192]]


# Creating modules

In [25]:
class saludar(object):
    def __init__(self, nombreMundo):
        self._nombreMundo = nombreMundo
    
    def __str__(self):
        return f"Joder {self._nombreMundo}"
        
    def imprimir(self):
        print("Hola mundo " + self._nombreMundo)
        

x = saludar("Terricola")
y = saludar("Avicola")

x.imprimir()      
y.imprimir()      

print(y)
print(x)
    

Hola mundo Terricola
Hola mundo Avicola
Joder Avicola
Joder Terricola


In [19]:
import cv2
import numpy

img = cv2.imread("sources/estatua.jpg")

#Aplicar un facot de borrosidad a la imagen
#blurredSrc = cv2.medianBlur(img, 7)
#graySrc = cv2.cvtColor(blurredSrc, cv2.COLOR_BGR2GRAY)     

graySrc = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) 
cv2.Laplacian(graySrc, cv2.CV_8U, graySrc)  
normalizedInverseAlpha = (1.0 / 255) * (255 - graySrc)

cv2.imshow("sin filtro", img)
cv2.imshow("filtro1", blurredSrc)
cv2.imshow("filtro2", graySrc)

channels = cv2.split(img)
cont = 0
for channel in channels:
    cont += 1
    channel[:]= channel * normalizedInverseAlpha ##1.5
    cv2.imshow(str(cont), channel)
    

nuevaImagen = cv2.merge(channels)
cv2.imshow("nuevaImagen", nuevaImagen)
cv2.waitKey()
cv2.destroyAllWindows()


kernel = numpy.array([[-1, -1, -1],
                      [-1,  10, -1],
                      [-1, -1, -1]])


nuevaImagen2 = cv2.filter2D(nuevaImagen, -1, kernel)

cv2.imshow("nuevaImagen2", nuevaImagen2)

cv2.waitKey()
cv2.destroyAllWindows()

# Detección de bordes con Canny

OpenCV ofrece una práctica función llamada (por el inventor del algoritmo, John F. Canny), que es muy popular no solo por su efectividad, sino también por la simplicidad de su implementación en un programa OpenCV, ya que es una sola línea:Canny

In [85]:
import cv2
import numpy as np

img = cv2.imread("sources/estatua.jpg", 0)
cv2.imwrite("canny.jpg", cv2.Canny(img, 200, 300))  # Canny in one line!
cv2.imshow("canny", cv2.imread("canny.jpg"))
cv2.waitKey()
cv2.destroyAllWindows()





# Detección de contornos

Una tarea vital en la visión artificial es la detección de contornos. Queremos detectar contornos o contornos de sujetos contenidos en una imagen o cuadro de vídeo, no sólo como un fin en sí mismo, sino también como un paso hacia otras operaciones. Estas operaciones son, a saber, calcular polígonos delimitadores, aproximar formas y, en general, calcular regiones de interés (ROI). Los ROI simplifican considerablemente la interacción con los datos de imagen porque una región rectangular en NumPy se define fácilmente con un segmento de matriz. Utilizaremos mucho la detección de contornos y el ROI cuando exploremos los conceptos de detección de objetos (incluida la detección de rostros) y seguimiento de objetos en capítulos posteriores.

Vamos a familiarizarnos con la API de detección de contornos a través de un ejemplo:

In [78]:
import cv2
import numpy as np
img = np.zeros((200,200), dtype=np.uint8)
#print(img)
img[50:150, 50:150] = 255
print(img)

cv2.imshow("contours", img)
cv2.waitKey()
cv2.destroyAllWindows()


#Encontrar puntos de mayor brillo
ret, thresh = cv2.threshold(img, 127, 255, 0)

#Encontrar contornos
contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
print(contours)
print(hierarchy)

color = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)

img = cv2.drawContours(color, contours, -1, (0,255,255), 2)
cv2.imshow("contours", color)
cv2.waitKey()
cv2.destroyAllWindows()


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(array([[[ 50,  50]],

       [[ 50, 149]],

       [[149, 149]],

       [[149,  50]]], dtype=int32),)
[[[-1 -1 -1 -1]]]


Primero, creamos una imagen negra vacía que tiene un tamaño de 200 x 200 píxeles. Luego, colocamos un cuadrado blanco en el centro utilizando la capacidad de la matriz para asignar valores en una rebanada.

Luego, fijamos el umbral de la imagen y llamamos a la función. Esta función tiene tres parámetros: la imagen de entrada, el tipo de jerarquía y el método de aproximación de contornos. El segundo parámetro especifica el tipo de árbol jerárquico devuelto por la función. Uno de los valores admitidos es , que indica a la función que recupere toda la jerarquía de contornos externos e internos. Estas relaciones pueden importar si estamos buscando objetos más pequeños (o regiones más pequeñas) dentro de objetos más grandes (o regiones más grandes). Si sólo desea recuperar la mayoría de los contornos externos, utilice . Esta puede ser una buena opción en los casos en que los objetos aparecen sobre un fondo plano y no nos importa encontrar objetos dentro de los objetos.findContourscv2.RETR_TREE cv2.RETR_EXTERNAL

Volviendo al ejemplo de código, observe que la función devuelve dos elementos: los contornos y su jerarquía. Usamos los contornos para dibujar contornos verdes en la versión en color de la imagen. Finalmente, mostramos la imagen.findContours

El resultado es un cuadrado blanco con su contorno dibujado en verde, ¡una escena espartana, pero efectiva para demostrar el concepto! Pasemos a ejemplos más significativos.



# Detección de contornos


Una tarea vital en la visión artificial es la detección de contornos. Queremos detectar contornos o contornos de sujetos contenidos en una imagen o cuadro de vídeo, no sólo como un fin en sí mismo, sino también como un paso hacia otras operaciones. Estas operaciones son, a saber, calcular polígonos delimitadores, aproximar formas y, en general, calcular regiones de interés (ROI). Los ROI simplifican considerablemente la interacción con los datos de imagen porque una región rectangular en NumPy se define fácilmente con un segmento de matriz. Utilizaremos mucho la detección de contornos y el ROI cuando exploremos los conceptos de detección de objetos (incluida la detección de rostros) y seguimiento de objetos en capítulos posteriores.

Vamos a familiarizarnos con la API de detección de contornos a través de un ejemplo:

In [119]:
import cv2
import numpy as np

img = cv2.pyrDown(cv2.imread("sources/figura.jpg"))
ret, thresh = cv2.threshold(cv2.cvtColor(img, cv2.COLOR_BGR2GRAY), 100, 255, cv2.THRESH_BINARY)
contours, hier = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

for c in contours:
    #encuentre las coredenadas
    x, y , w, h = cv2.boundingRect(c)
    cv2.rectangle(img, (x, y), (x+w, y+h),(0, 255, 0), 2)
    
    #Encontrar area minima
    rect = cv2.minAreaRect(c)
    
    #Clacular el area minimo de area del rectangulo
    box=cv2.boxPoints(rect)
    
    #normalizar cordenadas a enteros
    box = np.int0(box)

    #dibiujar contornos
    cv2.drawContours(img, [box], 0, (0, 0, 255), 3)
    
    #Calcular  centro y radio del circulo
    
    (x, y), radius = cv2.minEnclosingCircle(c)
    
    #Castear enteros
    center = (int(x), int(y))
    radius = int(radius)
    
    #draw the circle
    img = cv2.circle(img, center, radius, (0, 255, 0), 2)
    

cv2.drawContours(img, contours, -1, (255, 0, 0), 1)
cv2.imshow("contours", img)
cv2.waitKey()
cv2.destroyAllWindows()

# Contornos convexos y el algoritmo de Douglas-Peucker

Cuando trabajamos con contornos, podemos encontrar sujetos con diversas formas, incluidas las convexas. Una forma convexa es aquella en la que no hay dos puntos dentro de esta forma cuya línea de conexión vaya fuera del perímetro de la forma misma.

La primera facilidad que ofrece OpenCV para calcular el polígono delimitador aproximado de una forma es . El nombre de la función significa el algoritmo de Douglas-Peucker. Esta función toma tres parámetros:cv2.approxPolyDPDP


Un contorno.
Un valor épsilon que representa la discrepancia máxima entre el contorno original y el polígono aproximado (cuanto menor sea el valor, más cerca estará el valor aproximado del contorno original).
Una bandera booleana. Si es , significa que el polígono está cerrado.True

El valor épsilon es de vital importancia para obtener un contorno útil, así que entendamos lo que representa. Épsilon es la diferencia máxima entre el perímetro del polígono aproximado y el perímetro del contorno original. Cuanto menor sea esta diferencia, más similar será el polígono aproximado al contorno original.

Puede que te preguntes por qué necesitamos un polígono aproximado cuando tenemos un contorno que ya es una representación precisa. La respuesta a esto es que un polígono es un conjunto de líneas rectas, y muchas tareas de visión artificial se vuelven más simples si podemos definir polígonos para que delimiten regiones para su posterior manipulación y procesamiento.

Ahora que sabemos qué es un épsilon, necesitamos obtener información del perímetro de contorno como valor de referencia. Esto se puede obtener con la función de OpenCV:cv2.arcLength

    epsilon = 0.01 * cv2.arcLength(cnt, True)
    approx = cv2.approxPolyDP(cnt, epsilon, True)

Efectivamente, estamos instruyendo a OpenCV para calcular un polígono aproximado cuyo perímetro solo puede diferir del contorno original por una relación épsilon, específicamente, el 1% de la longitud del arco original.

OpenCV también ofrece una función para obtener información de contorno procesada para formas convexas. Esta es una expresión directa de una línea:cv2.convexHull

    hull = cv2.convexHull(cnt)
    
Vamos a combinar el contorno original, el contorno poligonal aproximado y el casco convexo en una sola imagen para observar las diferencias entre ellos. Para simplificar las cosas, dibujaremos los contornos sobre un fondo negro para que el sujeto original no sea visible pero sus contornos sean:

![imagen.png](attachment:imagen.png)


Figura 3.4c: Resultados de la detección de contornos seguida de la detección de casco de contexto y aproximación de polígonos.
Como puede ver, el casco convexo rodea todo el sujeto, el polígono aproximado es la forma de polígono más interno, y entre los dos está el contorno original, compuesto principalmente de arcos.

Al combinar todos los pasos anteriores en un script que carga un archivo, encuentra contornos, aproxima los contornos como un polígono, encuentra un casco convexo y muestra una visualización, tenemos el siguiente código:



In [23]:
import cv2
import numpy as np

img = cv2.pyrDown(cv2.imread("sources/figura.jpg"))
ret, thresh = cv2.threshold(cv2.cvtColor(img, cv2.COLOR_BGR2GRAY), 127, 255, cv2.THRESH_BINARY)

cv2.imshow("original", img)
cv2.imshow("thresh", thresh)

contours, hier = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)


black = np.zeros_like(img)

for cnt in contours:
    
    epilson = 0.01 * cv2.arcLength(cnt, True)
    #approx = cv2.approxPolyDP(cnt,epilson,True)
    approx = cv2.approxPolyDP(cnt,epilson,True)

    #rint(approx)
    #hull = cv2.convexHull(cnt)
    
    cv2.drawContours(black, [cnt], -1, (255, 2, 0), 2)
    cv2.drawContours(black, [approx], -1, (255, 255, 0), 2)
    #cv2.drawContours(black, [hull], -1, (0, 0, 255), 2)

cv2.imshow("hull", black)
cv2.waitKey()
cv2.destroyAllWindows()

# Detecting lines, circles, and other shapes

Detectar bordes y encontrar contornos no solo son tareas comunes e importantes por derecho propio; También forman la base de otras operaciones complejas. La detección de líneas y formas camina de la mano con la detección de bordes y contornos, así que examinemos cómo OpenCV los implementa.

La teoría detrás de la detección de líneas y formas tiene su fundamento en una técnica llamada transformada de Hough, inventada por Richard Duda y Peter Hart, quienes extendieron y generalizaron el trabajo realizado por Paul Hough a principios de la década de 1960. Echemos un vistazo a la API de OpenCV para transformaciones Hough.

Detección de líneas
En primer lugar, vamos a detectar algunas líneas. Podemos hacer esto con la función o la función. El primero usa la transformada de Hough estándar, mientras que el segundo usa la transformada de Hough probabilística (de ahí el en el nombre). La versión probabilística se llama así porque solo analiza un subconjunto de los puntos de la imagen y estima la probabilidad de que todos estos puntos pertenezcan a la misma línea. Esta implementación es una versión optimizada de la transformada estándar de Hough; Es menos intensivo computacionalmente y se ejecuta más rápido. se implementa de modo que devuelve los dos puntos finales de cada segmento de línea detectado, mientras que se implementa de modo que devuelve una representación de cada línea como un único punto y un ángulo, sin información sobre los puntos finales.HoughLinesHoughLinesPPHoughLinesPHoughLines


https://www.youtube.com/watch?v=zbyn57jgWNg

Echemos un vistazo a un ejemplo muy simple:



In [26]:
import cv2
import numpy as np

img = cv2.imread("sources/tren.jpg")
gris = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

#Sacar los bordes, se hace sobre el gris para evitar ruidos molestos
bordes = cv2.Canny(gris, 150, 255)

#Sacar la lineas con algoritmo de HOUGH
lineas = cv2.HoughLinesP(bordes,
                        rho=1,
                        theta=np.pi/180.0,
                        threshold=20,
                        minLineLength=80,
                        maxLineGap=5)

print(len(lineas))
for linea in lineas:
    x1, y1, x2, y2 = linea[0]
    cv2.line(img, (x1, y1), (x2, y2), (0, 255, 0), 2)



cv2.imshow("img", img)
cv2.imshow("gris", gris)
cv2.imshow("bordes", bordes)



cv2.waitKey()
cv2.destroyAllWindows()


43


Una parte crucial de este script simple, como parte de la llamada a la función, es establecer la longitud de línea mínima (se descartarán las líneas más cortas) y el espacio de línea máximo, que es el tamaño máximo de un espacio en una línea antes de que los dos segmentos comiencen a considerarse como líneas separadas.HoughLines

Además, tenga en cuenta que la función toma una imagen binaria de un solo canal, que se procesa a través del filtro de detección de bordes Canny. Canny no es un requisito estricto, pero una imagen que ha sido denoizada y solo representa bordes es la fuente ideal para una transformada de Hough, por lo que encontrará que esta es una práctica común.HoughLines

Los parámetros de son los siguientes: HoughLinesP

* La imagen binaria de Canny u otro filtro de detección de bordes.
* La resolución o el tamaño de paso que se va a usar al buscar líneas ```rho```. es el tamaño del paso posicional en píxeles, mientras ```theta``` que es el tamaño del paso de rotación en radianes. Por ejemplo, si especificamos ```rho=1``` y ```theta=np.pi/180.0``` encontramos líneas que están separadas por tan solo 1 píxel y 1 grado.
* El ```thresholdthreshold```, representa el umbral por debajo del cual se descarta una línea. La transformada de Hough funciona con un sistema de contenedores y votos, con cada contenedor representando una línea, por lo que si una línea candidata tiene al menos el número de votos del ```threshold```, se conserva; de lo contrario, se descarta.

*  Un argumento opcional ```lines```, el cual no usamos aqui y que no representa realmente un usop masivo en la funcion de python, el argumento `lines` se puiede usar para proveer una nueva lista in la cual ```HoughLinesP```colocara el resultado de lineas; de otro lado este retornara una nueva lista

* establece la longitud mínima de la línea (se descartarán las líneas más cortas) y la brecha de línea máxima, que es el tamaño máximo de una brecha en una línea antes de que los dos segmentos comiencen a considerarse como líneas separadas.

# Detecting circles
OpenCV también tiene una función para detectar círculos, llamada `HoughCircles`. Funciona de una manera muy similar a `HoughLines`, pero donde `minLineLength`y `maxLineGap`fueron los parámetros utilizados para descartar o retener líneas, `HoughCircles`en su lugar nos permite especificar una distancia mínima entre los centros de un círculo, así como valores mínimos y máximos para el radio de un círculo. Aquí está el ejemplo obligatorio:



In [1]:
import cv2
import numpy as np
planetas = cv2.imread("sources/planetas.jpg")
gris =  cv2.cvtColor(planetas, cv2.COLOR_BGR2GRAY)

#Suavizado de la imagen
gris2 = cv2.medianBlur(gris, 9)

#Sacar circulos
circulos = cv2.HoughCircles(gris2, cv2.HOUGH_GRADIENT, 1, 80, param1=100, param2=25, minRadius=0, maxRadius=0)
#print(circulos)

#Redondear los parametros a entero
circulos = np.uint16(np.around(circulos))
#print(circulos)

for i in circulos[0]:
    #Desempaquetar los valores del frame
    x, y, z = i
    
    #dibujar fuera del circulo
    cv2.circle(planetas, (x, y), z, (0, 255, 0), 2)
    
    #Dibujar el centro del circulo, el argumento "2" entabla el radio
    cv2.circle(planetas, (x, y), 2, (0, 0, 255), 3)

cv2.imshow("imagenOriginal", planetas)
cv2.imshow("grises", gris)
cv2.imshow("grises2", gris2)
cv2.waitKey()
cv2.destroyAllWindows()


# Detecting other shapes

Las implementaciones de OpenCV de la transformación de Hough se limitan a detectar líneas y círculos; Sin embargo, ya exploramos implícitamente la detección de formas en general cuando hablamos de `approxPolyDP`. Esta función permite la aproximación de polígonos, por lo que si su imagen contiene polígonos, se detectarán con precisión mediante el uso combinado de `cv2.findContours` y .