Optionally, we may specify the mode of imread. The supported options include the following:


cv2.IMREAD_COLOR: This is the default option, providing a 3-channel BGR image with an 8-bit value (0-255) for each channel.
cv2.IMREAD_GRAYSCALE: This provides an 8-bit grayscale image.
cv2.IMREAD_ANYCOLOR: This provides either an 8-bit-per-channel BGR image or an 8-bit grayscale image, depending on the metadata in the file.
cv2.IMREAD_UNCHANGED: This reads all of the image data, including the alpha or transparency channel (if there is one) as a fourth channel.
cv2.IMREAD_ANYDEPTH: This loads an image in grayscale at its original bit depth. For example, it provides a 16-bit-per-channel grayscale image if the file represents an image in this format.
cv2.IMREAD_ANYDEPTH | cv2.IMREAD_COLOR: This combination loads an image in BGR color at its original bit depth.
cv2.IMREAD_REDUCED_GRAYSCALE_2: This loads an image in grayscale at half its original resolution. For example, if the file contains a 640 x 480 image, it is loaded as a 320 x 240 image.
cv2.IMREAD_REDUCED_COLOR_2: This loads an image in 8-bit-per-channel BGR color at half its original resolution.
cv2.IMREAD_REDUCED_GRAYSCALE_4: This loads an image in grayscale at one-quarter of its original resolution.
cv2.IMREAD_REDUCED_COLOR_4: This loads an image in 8-bit-per-channel color at one-quarter of its original resolution.
cv2.IMREAD_REDUCED_GRAYSCALE_8: This loads an image in grayscale at one-eighth of its original resolution.
cv2.IMREAD_REDUCED_COLOR_8: This loads an image in 8-bit-per-channel color at one-eighth of its original resolution.


##    LECTURA Y ESCRITURA DE IMAGENES

In [1]:
import cv2 as cv
import sys

img = cv.imread(cv.samples.findFile("sources/emblema.jpg") )

if img is None:
    sys.exit("No se puede mostrar el archivo")
    
cv.imshow("Ventana de muestra", img)
k = cv.waitKey(0)

if k == ord("s"):
    cv.imwrite("sources/salida de imagen.png", img)
elif k == ord("q"):
    cv.destroyAllWindows()



In [13]:
import cv2 as cv
import sys

#img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_COLOR)
#img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_GRAYSCALE)
#img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_UNCHANGED )
#img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_ANYDEPTH )
#img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_ANYDEPTH | cv.IMREAD_COLOR )
#img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_REDUCED_GRAYSCALE_2 )
#img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_REDUCED_COLOR_2 )
#img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_REDUCED_GRAYSCALE_4 )
#img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_REDUCED_COLOR_4 )
#img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_REDUCED_GRAYSCALE_8 )
img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_REDUCED_COLOR_8 )


if img is None:
    sys.exit("No se puede mostrar el archivo")
    
cv.imshow("Ventana de muestra", img)
k = cv.waitKey(0)

if k == ord("s"):
    cv.imwrite("sources/salida de imagen.png", img)
elif k == ord("q"):
    cv.destroyAllWindows()
    
print (img)
print(img.shape)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
(136, 240, 3)


As an example, let's load a PNG file as a grayscale image (losing any color information in the process), and then save it as a grayscale PNG image:

In [9]:
import cv2 as cv
import sys

#grayImage = cv.imread('sources/goku.png', cv.IMREAD_GRAYSCALE)
grayImage = cv.imread('sources/goku.png', cv.IMREAD_REDUCED_COLOR_8)

if grayImage is None:
    print('Failed to read image from file')
    sys.exit(1)
success = cv.imwrite('sources/gokuOut.png', grayImage)
if not success:
    print('Failed to write image to file')
    sys.exit(1)
    
print (grayImage)
print(grayImage.shape)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(200, 146, 3)


## Video
### captura de video camara

In [9]:
import numpy as np

cap = cv.VideoCapture(2)
if not cap.isOpened():
    print("No es posible abrir la camara")
    exit()
    
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    
    # if frame is read correctly ret is True
    if not ret:
        print("No se puede recibir datos (stream end?). Exiting ...")
        break
        
    # Our operations on the frame come here
    #gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
    # Display the resulting frame
    #cv.imshow('mostrador Video', gray)
    
    
    cv.imshow('mostrador Video', frame)
    if cv.waitKey(1) == ord('q'):
        break
# When everything done, release the capture
cap.release()
cv.destroyAllWindows()
    



### Leyendo video

Antes de instalar asegurarse de la version de ffmpeg o gstreamer esté instalado previamente, algunas veces arroga error por este tipo de dependencias

In [1]:
import numpy as np
#import cv2 as cv
cap = cv.VideoCapture('sources/flores.mp4')
while cap.isOpened():
    ret, frame = cap.read()
    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
    
    cv.imshow('frame', gray)
    if cv.waitKey(1) == ord('q'):
        break
cap.release()
cv.destroyAllWindows()

NameError: name 'cv' is not defined

### Guardando video

Antes de instalar asegurarse de la version de ffmpeg o gstreamer esté instalado previamente, algunas veces arroga error por este tipo de dependencias


In [2]:
import numpy as np
#import cv2 as cv
cap = cv.VideoCapture(2)
# Define the codec and create VideoWriter object
fourcc = cv.VideoWriter_fourcc(*'XVID')
out = cv.VideoWriter('sources/output.mp4', fourcc, 20.0, (3840,  2160))
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    frame = cv.flip(frame, 0)
    # write the flipped frame
    out.write(frame)
    cv.imshow('frame', frame)
    if cv.waitKey(1) == ord('q'):
        break
# Release everything if job is finished
cap.release()
out.release()
cv.destroyAllWindows()

# propiedades del imread

In [ ]:
import cv2 as cv

