# Numpy

In [2]:
import numpy as np

#Primer acercamiento conj mumpy creando una imagen
img = np.zeros((3,3), dtype = np.uint8)
print(img)



[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [3]:
#vamos a crear una imagen gris con la funcion  cvtcolor de open cv

import cv2 as cv

img = cv.cvtColor(img, cv.COLOR_GRAY2BGR)
print(img)

cv.imshow("mostrador", img)


cv.waitKey(0)
cv.destroyAllWindows()

print(img.shape)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
(3, 3, 3)


In [1]:
img = np.zeros((5, 3), dtype=np.uint8)
print(img.shape)
print(img)

NameError: name 'np' is not defined

In [17]:
import numpy as np
import cv2 as cv

img = np.zeros((3,3), dtype = np.uint8)
print(img)
print("------------------")

img = cv.cvtColor(img, cv.COLOR_GRAY2BGR)
img2 = cv.cvtColor(img, cv.IMREAD_COLOR)
print(img)
print("------------------")

print(img2)
print("------------------")

#Grises
byteArray = bytearray(img)
print(byteArray)
print("------------------")

grayImage = np.array(byteArray).reshape(9, 3)
print(grayImage)
print("------------------")

#Color BGR
byteBgrArray=bytearray(img2)
print(byteBgrArray)
print("------------------")

bgrImage = np.array(byteBgrArray).reshape(3, 3, 3)
print(bgrImage)
print("------------------")

[[0 0 0]
 [0 0 0]
 [0 0 0]]
------------------
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
------------------
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
------------------
bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
------------------
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
------------------
bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
------------------
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
------------------


In [18]:

import cv2
import numpy
import os

# Make an array of 120,000 random bytes.
randomByteArray = bytearray(os.urandom(120000))
print(randomByteArray)
print("------------------")

flatNumpyArray = numpy.array(randomByteArray)
print(flatNumpyArray)
print("------------------")

# Convert the array to make a 400x300 grayscale image.
grayImage = flatNumpyArray.reshape(300, 400)
cv2.imwrite('sources/RandomGray.png', grayImage)
print(grayImage)
print("------------------")

# Convert the array to make a 400x100 color image.
bgrImage = flatNumpyArray.reshape(100, 400, 3)
cv2.imwrite('sources/RandomColor.png', bgrImage)



bytearray(b'\x1f\x81\x8a\xe8<\xdff\xc0\x00\x15\xa8\x10\xa1\xf4\x1a\x11y\xa8\xc73\xd1\xb1g\xa6\xe9\xe5\xb8\x92\x0e\xa6b\xa0\xe78=\x83\xfb1I84^\x14j\x08\xae\xd6\xf9\xa5\xc1J\x88=\x03\xd9\nGqD\x87L;\x88j\xe1\xd5\xdd\x97\xcb\xfe\x16\xd3C!d?Eb\xd5C+^~\x17NI\x7f\xe1\xaf\xc9dcm\xd63V\xd5\x1a]\x00Q~\xaa\xb6\x91\xf5\xb48\xdb8u\x80\x89\xa8#\x0b\xd1\xb0\r.\x00\xb4\xc7;\xd4\xca\xe8\x19\xab\x07\x9b\x15\x98F\x8e\xab\xc4\xe7\xe1\xc1\xe7\x8eub\xbc\x90;\xc2\x8f\xf3\\k\xb0\xe0\x90\xbe\x18bXf)\x02\x8d\xbd5\xf7\rIG\xa4(\xcd\x9d\xb2\x89V\x05mI\x12_m\xa8O\x1f\xbb\xb3\xbf)\xb8\xa7,\xe0\xc9\x93\xa8\x1d\xc6\xb5\xe6\xbar\xe9\x06\x8c\x81\xa6\xff%2\nP#9\xc3\x80!P\xf1\xba\x05X\xa6\xf3\xcf:\x11\xb3oiQo\xf2\x07{\xbf9\r\n\xfe\x9f3;\x17m\xe3\xd5k+\xb24d:\xe1\x9e>\xe8\x9b\xc2\x19\xa3\xe1`w\x17\xf62\xe01\x1fy\xbd\xe7d\xb9`\xb6\xecr_c\xb3\x1a\xc5\xd6t\xbe\xd6\xac\xf6T\x835\xf8\xffPK\xff\xd1\r\x1c&\x9d6\xf8\xc0"GU\xd3ZB\xbd\x03k\xc6\xf6\xb1\xe9\xaf\xdc=\xa6M\r\xb0}%Z:=B#p\xc4\x06\xc5\xee\xf2^\xbe\xdd\xbd\xaf\x9f\x06\x01\r

True

# Accessing image data with numpy.array

In [44]:
import cv2 as cv

img = cv.imread('sources/goku.png')

for i in range(1170):
    for j in range(100):
        img[200+j, i] = [200, 0, 0]
    

cv.imshow("imagen", img)
k = cv.waitKey(0)
cv.destroyAllWindows()

In [23]:
import cv2

img = cv2.imread('sources/goku.png')

#Para establecer  la funcion de cambiar un  pixel 
#img.itemSet (posX, posY, posRGB), valor a cambiar)
img.itemset((10, 10, 2), 255)
cv.imshow("imagen",img)
k = cv.waitKey(0)
cv.destroyAllWindows()

print(img.item(10, 10, 2))


255


In [22]:
#import cv2

img = cv2.imread('sources/goku.png')

#tercer item es el BRG
img[:, :, 2] = 255
cv.imshow("imagen",img)
k = cv.waitKey(0)
cv.destroyAllWindows()


In [52]:
##Copiar y pegar de una imagen a otra


import cv2
img = cv2.imread('sources/goku.png')
my_roi = img[300:500, 500:700]
img[500:700, 700:900] = my_roi
img[0:200, 0:200] = my_roi



cv.imshow("imagen",img)
k = cv.waitKey(0)
cv.destroyAllWindows()



# conocer los tamaños de una imagen

* shape: This is a tuple describing the shape of the array. For an image, it contains (in order) the height, width, and—if the image is in color—the number of channels. The length of the shape tuple is a useful way to determine whether an image is grayscale or color. For a grayscale image, we have len(shape) == 2, and for a color image, len(shape) == 3.

* size: This is the number of elements in the array. In the case of a grayscale image, this is the same as the number of pixels. In the case of a BGR image, it is three times the number of pixels because each pixel is represented by three elements (B, G, and R).

* dtype: This is the datatype of the array's elements. For an 8-bit-per-channel image, the datatype is numpy.uint8.



In [53]:
##Conocer los tamaños de una imagen
import cv2
img = cv2.imread('sources/goku.png')
print(img.shape)
print(img.size)
print(img.dtype)


(1600, 1170, 3)
5616000
uint8


# Converting between numpy.array and cv2.UMat

Currently, cv2.UMat supports GPU acceleration on systems that have OpenCL-compliant GPU drivers, with a minimum version of OpenCL 1.2. Most modern desktop or laptop GPUs, as well as some high-end smartphone or tablet GPUs, have this level of OpenCL support.


The following code initializes a UMat by copying data from a NumPy array:


`my_umat = cv2.UMat(my_numpy_array)`


Most OpenCV functions will accept a UMat argument in place of NumPy array and, then, will return a UMat instead of NumPy array. Here is an example:


`my_converted_umat = cv2.cvtColor(my_umat, cv2.COLOR_GRAY2BGR)`

NumPy functions will not accept a UMat argument, a UMat does not have the same methods as a numpy.array, and we cannot perform slicing or other Pythonic operations on UMat data. However, we can convert a UMat back to a NumPy array, as follows:

`my_converted_numpy_array = my_converted_umat.get()`

Tal vez se pregunte, ¿debería comenzar a usar s en todas partes para acelerar sus aplicaciones? Probablemente no. Copiar datos dentro y fuera de la memoria de la GPU es una operación costosa y, en muchos casos, este costo general supera el beneficio de un mayor paralelismo en la GPU. Por otro lado, si puede minimizar el número de copias y si puede aplicar una serie de funciones OpenCV a una gran cantidad de datos en la GPU, entonces el beneficio puede superar el costo.UMat

A lo largo de este libro, usaremos principalmente en lugar de , pero tenga en cuenta que es posible que desee probar el rendimiento de como alternativa para sus propias aplicaciones prácticas.

`numpy.arraycv2.UMatcv2.UMat` 






In [8]:
import cv2
import numpy as np

img = cv2.imread('sources/goku.png', cv2.IMREAD_GRAYSCALE)

my_umat = cv2.UMat(img)


cv2.imshow("imagen",my_umat)
k = cv2.waitKey(0)
cv2.destroyAllWindows()


nuevoNumpyImagen = my_umat.get()
cv2.imshow("imagen",nuevoNumpyImagen)
k = cv2.waitKey(0)
cv2.destroyAllWindows()



print(my_umat)
print(nuevoNumpyImagen)

< cv2.UMat 000001AB66536670>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
