Optionally, we may specify the mode of imread. The supported options include the following:


cv2.IMREAD_COLOR: This is the default option, providing a 3-channel BGR image with an 8-bit value (0-255) for each channel.
cv2.IMREAD_GRAYSCALE: This provides an 8-bit grayscale image.
cv2.IMREAD_ANYCOLOR: This provides either an 8-bit-per-channel BGR image or an 8-bit grayscale image, depending on the metadata in the file.
cv2.IMREAD_UNCHANGED: This reads all of the image data, including the alpha or transparency channel (if there is one) as a fourth channel.
cv2.IMREAD_ANYDEPTH: This loads an image in grayscale at its original bit depth. For example, it provides a 16-bit-per-channel grayscale image if the file represents an image in this format.
cv2.IMREAD_ANYDEPTH | cv2.IMREAD_COLOR: This combination loads an image in BGR color at its original bit depth.
cv2.IMREAD_REDUCED_GRAYSCALE_2: This loads an image in grayscale at half its original resolution. For example, if the file contains a 640 x 480 image, it is loaded as a 320 x 240 image.
cv2.IMREAD_REDUCED_COLOR_2: This loads an image in 8-bit-per-channel BGR color at half its original resolution.
cv2.IMREAD_REDUCED_GRAYSCALE_4: This loads an image in grayscale at one-quarter of its original resolution.
cv2.IMREAD_REDUCED_COLOR_4: This loads an image in 8-bit-per-channel color at one-quarter of its original resolution.
cv2.IMREAD_REDUCED_GRAYSCALE_8: This loads an image in grayscale at one-eighth of its original resolution.
cv2.IMREAD_REDUCED_COLOR_8: This loads an image in 8-bit-per-channel color at one-eighth of its original resolution.


##    LECTURA Y ESCRITURA DE IMAGENES

In [1]:
import cv2 as cv
import sys

img = cv.imread(cv.samples.findFile("sources/emblema.jpg") )

if img is None:
    sys.exit("No se puede mostrar el archivo")
    
cv.imshow("Ventana de muestra", img)
k = cv.waitKey(0)

if k == ord("s"):
    cv.imwrite("sources/salida de imagen.png", img)
elif k == ord("q"):
    cv.destroyAllWindows()



In [13]:
import cv2 as cv
import sys

#img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_COLOR)
#img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_GRAYSCALE)
#img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_UNCHANGED )
#img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_ANYDEPTH )
#img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_ANYDEPTH | cv.IMREAD_COLOR )
#img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_REDUCED_GRAYSCALE_2 )
#img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_REDUCED_COLOR_2 )
#img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_REDUCED_GRAYSCALE_4 )
#img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_REDUCED_COLOR_4 )
#img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_REDUCED_GRAYSCALE_8 )
img = cv.imread(cv.samples.findFile("sources/emblema.jpg"), cv.IMREAD_REDUCED_COLOR_8 )


if img is None:
    sys.exit("No se puede mostrar el archivo")
    
cv.imshow("Ventana de muestra", img)
k = cv.waitKey(0)

if k == ord("s"):
    cv.imwrite("sources/salida de imagen.png", img)
elif k == ord("q"):
    cv.destroyAllWindows()
    
print (img)
print(img.shape)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
(136, 240, 3)


As an example, let's load a PNG file as a grayscale image (losing any color information in the process), and then save it as a grayscale PNG image:

In [9]:
import cv2 as cv
import sys

#grayImage = cv.imread('sources/goku.png', cv.IMREAD_GRAYSCALE)
grayImage = cv.imread('sources/goku.png', cv.IMREAD_REDUCED_COLOR_8)

if grayImage is None:
    print('Failed to read image from file')
    sys.exit(1)
success = cv.imwrite('sources/gokuOut.png', grayImage)
if not success:
    print('Failed to write image to file')
    sys.exit(1)
    
print (grayImage)
print(grayImage.shape)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(200, 146, 3)


## Video
### captura de video camara

In [9]:
import numpy as np

cap = cv.VideoCapture(2)
if not cap.isOpened():
    print("No es posible abrir la camara")
    exit()
    
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    
    # if frame is read correctly ret is True
    if not ret:
        print("No se puede recibir datos (stream end?). Exiting ...")
        break
        
    # Our operations on the frame come here
    #gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
    # Display the resulting frame
    #cv.imshow('mostrador Video', gray)
    
    
    cv.imshow('mostrador Video', frame)
    if cv.waitKey(1) == ord('q'):
        break
# When everything done, release the capture
cap.release()
cv.destroyAllWindows()
    



### Leyendo video

Antes de instalar asegurarse de la version de ffmpeg o gstreamer esté instalado previamente, algunas veces arroga error por este tipo de dependencias

In [1]:
import numpy as np
#import cv2 as cv
cap = cv.VideoCapture('sources/flores.mp4')
while cap.isOpened():
    ret, frame = cap.read()
    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
    
    cv.imshow('frame', gray)
    if cv.waitKey(1) == ord('q'):
        break
cap.release()
cv.destroyAllWindows()

NameError: name 'cv' is not defined

### Guardando video

Antes de instalar asegurarse de la version de ffmpeg o gstreamer esté instalado previamente, algunas veces arroga error por este tipo de dependencias


In [2]:
import numpy as np
#import cv2 as cv
cap = cv.VideoCapture(2)
# Define the codec and create VideoWriter object
fourcc = cv.VideoWriter_fourcc(*'XVID')
out = cv.VideoWriter('sources/output.mp4', fourcc, 20.0, (3840,  2160))
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    frame = cv.flip(frame, 0)
    # write the flipped frame
    out.write(frame)
    cv.imshow('frame', frame)
    if cv.waitKey(1) == ord('q'):
        break
# Release everything if job is finished
cap.release()
out.release()
cv.destroyAllWindows()

# Guardar video

* 0: Esta opción es un archivo de vídeo sin comprimir. La extensión del archivo debe ser ..avi
* cv2.VideoWriter_fourcc('I','4','2','0'): Esta opción es una codificación YUV sin comprimir, submuestreo de croma 4:2:0. Esta codificación es ampliamente compatible, pero produce archivos grandes. La extensión del archivo debe ser ..avi
* cv2.VideoWriter_fourcc('P','I','M','1'): Esta opción es MPEG-1. La extensión del archivo debe ser ..avi
* cv2.VideoWriter_fourcc('X','V','I','D'): Esta opción es una codificación MPEG-4 relativamente antigua. Es una buena opción si desea limitar el tamaño del video resultante. La extensión del archivo debe ser ..avi
* cv2.VideoWriter_fourcc('M','P','4','V'): Esta opción es otra codificación MPEG-4 relativamente antigua. Es una buena opción si desea limitar el tamaño del video resultante. La extensión del archivo debe ser ..mp4
* cv2.VideoWriter_fourcc('X','2','6','4'): Esta opción es una codificación MPEG-4 relativamente nueva. Puede ser la mejor opción si desea limitar el tamaño del video resultante. La extensión del archivo debe ser ..mp4
* cv2.VideoWriter_fourcc('T','H','E','O'): Esta opción es Ogg Vorbis. La extensión del archivo debe ser .ogv

También se debe especificar una velocidad de fotogramas y un tamaño de fotograma. Como estamos copiando de otro video, estas propiedades se pueden leer desde el método get de la clase.VideoCapture

In [4]:

import cv2

videoCapture = cv2.VideoCapture('sources/flores.mp4')
fps = videoCapture.get(cv2.CAP_PROP_FPS)
print (fps)

size = (int(videoCapture.get(cv2.CAP_PROP_FRAME_WIDTH)),
        int(videoCapture.get(cv2.CAP_PROP_FRAME_HEIGHT)))
print(size)


videoWriter = cv2.VideoWriter(
    'sources/MyOutputVid.avi', cv2.VideoWriter_fourcc('I','4','2','0'),
    fps, size)

success, frame = videoCapture.read()
while success:  # Loop until there are no more frames.
    videoWriter.write(frame)
    success, frame = videoCapture.read()
    



60.0
(1920, 1080)



## Enabling hardware acceleration for video I/O

A menudo, las GPU modernas son capaces de acelerar los algoritmos que decodifican (leen) y codifican (escriben) algunos de los formatos de video comunes. De forma predeterminada, OpenCV y clases no intentan usar la aceleración de GPU; ejecutan los algoritmos de decodificación y codificación en la CPU. Sin embargo, a partir de OpenCV 4.5.2 y continuando en OpenCV 5, el soporte para la codificación/decodificación acelerada por GPU ha ido mejorando. Si modificamos nuestro ejemplo de E/S de vídeo de las formas resaltadas a continuación, OpenCV intentará utilizar la aceleración de GPU en sistemas compatibles:VideoCaptureVideoWriter



In [5]:
import cv2

videoCapture = cv2.VideoCapture(
    'sources/output.mp4', cv2.CAP_ANY,
    [cv2.CAP_PROP_HW_ACCELERATION, cv2.VIDEO_ACCELERATION_ANY])

fps = videoCapture.get(cv2.CAP_PROP_FPS)
size = (int(videoCapture.get(cv2.CAP_PROP_FRAME_WIDTH)),
        int(videoCapture.get(cv2.CAP_PROP_FRAME_HEIGHT)))

videoWriter = cv2.VideoWriter(
    'sources/MyOutputVid2.avi', cv2.VideoWriter_fourcc('I','4','2','0'), fps, size,
    [cv2.VIDEOWRITER_PROP_HW_ACCELERATION, cv2.VIDEO_ACCELERATION_ANY])
success, frame = videoCapture.read()
while success: # Loop until there are no more frames.
    videoWriter.write(frame)
    success, frame = videoCapture.read()

Aquí, los parámetros indican a la instancia que utilice cualquier back-end de captura disponible con cualquier back-end de aceleración disponible. Del mismo modo, el parámetro indica a la instancia que utilice cualquier back-end de aceleración disponible.cv2.CAP_ANY, [cv2.CAP_PROP_HW_ACCELERATION, cv2.VIDEO_ACCELERATION_ANY]VideoCapture[cv2.VIDEOWRITER_PROP_HW_ACCELERATION, cv2.VIDEO_ACCELERATION_ANY]VideoWriter

Actualmente, Windows es la plataforma mejor soportada, en términos del uso de OpenCV de codificación/decodificación acelerada por GPU. Algunas configuraciones de Linux también son compatibles. Un soporte más amplio puede estar disponible en futuras versiones de OpenCV 5.x. En sistemas donde OpenCV no admite codificación/decodificación acelerada por GPU, debería recurrir de forma segura a la codificación/decodificación de CPU. Tenga en cuenta que el soporte para la aceleración de GPU puede variar según el formato de video, así como el sistema operativo y el hardware.

For more information on the ongoing efforts to support GPU-accelerated encoding/decoding, see the OpenCV Wiki article at https://github.com/opencv/opencv/wiki/Video-IO-hardware-acceleration.


# Capturing camera frames

In [8]:
import cv2
cameraCapture = cv2.VideoCapture(2)
print(cameraCapture.get(cv2.CAP_PROP_FRAME_WIDTH))

fps = 30  # An assumption
size = (int(cameraCapture.get(cv2.CAP_PROP_FRAME_WIDTH)),
        int(cameraCapture.get(cv2.CAP_PROP_FRAME_HEIGHT)))

size

videoWriter = cv2.VideoWriter(
    'sources/MyOutputVid.avi', cv2.VideoWriter_fourcc('I','4','2','0'),
    fps, size)

success, frame = cameraCapture.read()
numFramesRemaining = 10 * fps - 1 # 10 seconds of frames
while success and numFramesRemaining > 0:
    videoWriter.write(frame)
    success, frame = cameraCapture.read()
    numFramesRemaining -= 1

640.0


In [9]:
success0 = cameraCapture0.grab()
success1 = cameraCapture1.grab()
if success0 and success1:
    frame0 = cameraCapture0.retrieve()
    frame1 = cameraCapture1.retrieve()

NameError: name 'cameraCapture0' is not defined